# Generated by Django 4.1.7 on 2023-04-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[[0, 'Nuevo en la actividad'], [1, 'Poco conocimiento'], [2, 'Bueno en la actividad'], [3, 'Avansado'], [4, 'Desconosco']])),
                ('dia', models.IntegerField(choices=[[0, 'Lunes'], [1, 'Martes'], [2, 'Miercoles'], [3, 'Jueves'], [4, 'Viernes'], [5, 'Sabado']], unique=True)),
                ('horario', models.IntegerField(choices=[[0, '10'], [1, '11'], [2, '13'], [3, '14'], [4, '15'], [5, '16'], [6, '17'], [7, '18'], [8, '19'], [9, '20']])),
                ('incapacidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comenta', models.CharField(max_length=30, unique=True)),
                ('email_comenta', models.EmailField(max_length=254)),
                ('tipo_coemtario', models.IntegerField(choices=[[0, 'Pocitivo'], [1, 'Neutral'], [2, 'Negativo']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.IntegerField(choices=[[0, 'Mi persona'], [1, 'Mi pareja'], [2, 'Mi hijo/hija'], [3, 'Otros']])),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30, unique=True)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'Otros']])),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profe', models.IntegerField(choices=[[0, 'Juan Topo'], [1, 'Tomas Ramirez'], [2, 'Maximo Decimo Meridio']], unique=True)),
                ('email_profe', models.EmailField(max_length=254)),
            ],
        ),
    ]
