# Generated by Django 4.1.7 on 2023-03-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscripcionNatacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre_profe',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
